/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTEGER_H_RPCGEN
#define _INTEGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct incr_in {
	int arg1;
};
typedef struct incr_in incr_in;

struct incr_out {
	int res1;
};
typedef struct incr_out incr_out;

#define INCR_PROG 0x31230000
#define INCR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INCRPROC 1
extern  incr_out * incrproc_1(incr_in *, CLIENT *);
extern  incr_out * incrproc_1_svc(incr_in *, struct svc_req *);
extern int incr_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INCRPROC 1
extern  incr_out * incrproc_1();
extern  incr_out * incrproc_1_svc();
extern int incr_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_incr_in (XDR *, incr_in*);
extern  bool_t xdr_incr_out (XDR *, incr_out*);

#else /* K&R C */
extern bool_t xdr_incr_in ();
extern bool_t xdr_incr_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTEGER_H_RPCGEN */
