/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTEGER_H_RPCGEN
#define _INTEGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MJLPROG 0x20000001
#define MJLVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INTEGER 1
extern  int * integer_1(int *, CLIENT *);
extern  int * integer_1_svc(int *, struct svc_req *);
extern int mjlprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INTEGER 1
extern  int * integer_1();
extern  int * integer_1_svc();
extern int mjlprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTEGER_H_RPCGEN */
