/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "integer.h"

bool_t
xdr_incr_in (XDR *xdrs, incr_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_incr_out (XDR *xdrs, incr_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res1))
		 return FALSE;
	return TRUE;
}
